package com.maybeitssquid.sensitive;

import java.util.Arrays;
import java.util.function.Function;

/**
 * A {@link Sensitive} value that can be backed by any array of items of the same type.
 *
 * @param <T> the type of the individual segments. This type should have well-defined {@link Object#equals(Object)} and
 *            {@link Object#hashCode()} methods so that the corresponding methods in this class meet the contract.
 */
public class SensitiveArray<T> extends Sensitive<T[]> {

    /**
     * Creates a wrapper for a sensitive array.
     *
     * @param sensitive the array to protect.
     */
    protected SensitiveArray(T[] sensitive) {
        super(sensitive);
    }

    /**
     * Returns a function that converts an array of protected character sequences into a single character sequence.
     *
     * @return function to generate the concatenated data.
     */
    public static Function<CharSequence[], CharSequence> concatenate() {
        return (t) -> String.join("", t);
    }

    /**
     * Returns a function that converts an array of protected character sequences into a delimited character sequence.
     *
     * @param delimiter delimiter between each element of the protected array.
     * @return function to generate the delimited data.
     */
    public static Function<CharSequence[], CharSequence> delimit(final CharSequence delimiter) {
        return (t) -> String.join(delimiter, t);
    }

    /**
     * Returns a function that converts an array of protected character sequences into a delimited character sequence.
     *
     * @param delimiter delimiter between each element of the protected array.
     * @return function to generate the delimited data.
     */
    public static Function<CharSequence[], CharSequence> delimit(final char delimiter) {
        return delimit(String.valueOf(delimiter));
    }

    /**
     * Returns a function that converts an array of protected elements into a delimited character sequence.
     *
     * @param delimiter delimiter between each element of the protected array.
     * @param extractor function to convert each element into a {@code CharSequence}
     * @param <T>       The type of sensitive data to be protected.
     * @return function to generate the delimited data.
     */
    public static <T> Function<T[], CharSequence> delimit(final CharSequence delimiter, final Function<T, CharSequence> extractor) {
        return (t) -> {
            final StringBuilder buffer = new StringBuilder();
            buffer.append(extractor.apply(t[0]));
            for (int i = 1; i < t.length; i++) buffer.append(delimiter).append(extractor.apply(t[i]));
            return buffer.toString();
        };
    }

    /**
     * Returns the hash of the enclosed {@code raw} data as generated by invoking {@link Arrays#hashCode(Object[])}
     * on the contained raw data.
     *
     * @return {@inheritDoc}
     */
    @Override
    public int hashCode() {
        return Arrays.hashCode(this.sensitive);
    }

    /**
     * Returns true if the types match and the enclosed raw data are equal as indicated by invoking
     * {@link Arrays#equals(Object[], Object[])}.
     *
     * @param o {@inheritDoc}
     * @return {@inheritDoc}
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        return Arrays.equals(sensitive, ((SensitiveArray<?>) o).sensitive);
    }
}
